homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: 33
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # DONE for SMO_IPHONE
  customize: !include_dir_merge_named Customize
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

ios:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

# Text to speech
tts:
  platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automation
#device_tracker: !include device_tracker.yaml 
zone: !include zones.yaml  

ffmpeg:
  
arlo:
  username: !secret arlo_username
  password: !secret arlo_password
sensor 2:
  - platform: arlo
    monitored_conditions:
      - captured_today
      - last_capture
      - total_cameras
camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'      
      
rfxtrx:
  device: /dev/ttyUSB0

light:
  - platform: rfxtrx
    automatic_add: True
  
switch:
  - platform: rfxtrx
    automatic_add: True
    devices:
      0b110000003c3a220b010f70:
        name: Lumiere Salon
      0A14050D00282701010000:
        name: Lumiere Chambre      
      0A14050D00282801010000:
        name: Lumiere Cuisine1
      0A14050D00282901000000:
        name: Lumiere Cuisine2      
cover:
  platform: rfxtrx
  automatic_add: True
  signal_repetitions: 1
  devices:
    071a000007270101: # RFY
      name: Volet Salon
    071a000007270201: # RFY
      name: Volet SAM
    071a000007270301: # RFY
      name: Volet Bureau
    071a000007270401: # RFY
      name: Volet Chambre
    071a000007270501: # RFY
      name: Volet Cuisine
    071a000007270601: # RFY
      name: Prise SAM      
      
      
input_select:
  arlo_mode:
    name: Arlo Mode
    options:
     - Enable
     - Disable
    initial: Enable
    icon: mdi:camera
 
notify: !include_dir_list Notify/
    
